env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:jest/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
  - 'prettier/react'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - jest
  - prettier
  - '@typescript-eslint'
settings:
  react:
    version: detect
  jest:
    version: 26
